// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package databasegen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ClientID pgtype.UUID
	Name     string
	Address  pgtype.Text
}

type Order struct {
	OrderID       pgtype.UUID
	ClientID      pgtype.UUID
	SubmittedDate string
}

type OrderProduct struct {
	OrderID   pgtype.UUID
	ProductID pgtype.UUID
	Amount    int32
}

type Product struct {
	ProductID pgtype.UUID
	Name      string
}

type User struct {
	UserID    pgtype.UUID
	LoginName string
}
